Repository ByteBam/ByteBamFronted, pull requests merged in 2024-04, with the labels that each got.

#8 fix(#3): rebuild ci check_commit_msg
  scripts/check_commit_msg.sh
Labels: bug

#25 fix(#20): hotfix workflows auto delete branch
  .github/workflows/auto_delete_branch.yml
Labels: bug, enhancement

#27 feat(#21): github ci bot support auto label
  .github/workflows/laber.yml
  .github/workflows/lable.json
Labels: enhancement, good first issue, feature

#21 feat(#19): 封装请求方法以及添加测试组件
  .env.development
  .env.production
  next.config.mjs
  pnpm-lock.yaml
  src/envVariable.ts
  src/utils/request.ts
Labels: good first issue, feature

#18 feat(#3): 引入antd
  package.json
  pnpm-lock.yaml
Labels: good first issue, feature
